# https://external-secrets.io/latest/introduction/getting-started/
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: default-parameter-store
  namespace: kube-system
spec:
  provider:
    aws:
      region: ap-northeast-2
      service: ParameterStore
---
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: default-secret-manager
  namespace: kube-system
spec:
  provider:
    aws:
      region: ap-northeast-2
      service: SecretsManager
