#apiVersion: external-secrets.io/v1beta1
#kind: ExternalSecret
#metadata:
#  name: secret
#  namespace: default
#spec:
#  refreshInterval: 30m
#  secretStoreRef:
#    name: default-parameter-store
#    kind: ClusterSecretStore
#  target:
#    name: secret
#    creationPolicy: Owner
#  data:
#    - secretKey: { { api-key } }
#      remoteRef:
#        key: { { ssm param alias } }
