---
# For System
---
apiVersion: v1
kind: Namespace
metadata:
  name: argocd
---
apiVersion: v1
kind: Namespace
metadata:
  name: karpenter
---
apiVersion: v1
kind: Namespace
metadata:
  name: keda
---
# For User
---
apiVersion: v1
kind: Namespace
metadata:
  name: fivessun
