{{- $files := .Files }}
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: external-secrets
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  generators:
    - merge:
        mergeKeys:
          - name
        generators:
          - clusters:
              values:
                targetRevision: 0.9.4
          - list:
              elements:
                - name: fivessun-1-27-ioewq
                  values:
                    roleArn: arn:aws:iam::629484894158:role/eks-external-secrets
  template:
    metadata:
      name: 'external-secrets-{{`{{name}}`}}'
    spec:
      destination:
        server: '{{`{{server}}`}}'
        namespace: external-secrets
      project: default
      source:
        repoURL: https://charts.external-secrets.io
        targetRevision: '{{`{{values.targetRevision}}`}}'
        chart: external-secrets
        helm:
          releaseName: external-secrets
          values: |
            {{- $files.Get "conf/external-secerts/default.yaml" | nindent 12 }}
            serviceAccount:
              create: true
              name: external-secrets
              annotations:
                eks.amazonaws.com/role-arn: '{{`{{values.roleArn}}`}}'
#      syncPolicy:
#        {{- toYaml .Values.argocd.syncPolicy | nindent 8 }}
