configs:
  cm:
    url: ""
    timeout.reconciliation: 15s
#    dex.config: |
#      connectors:
#      - type: github
#        id: github
#        name: GitHub
#        config:
#          clientID: fa41a9ad8f42f7e4be31
#          clientSecret: $dex.github.clientSecret
#          orgs:
#          - name: fivessun
    admin.enabled: false
    exec.enabled: true
  rbac:
    policy.default: role:readonly
    policy.csv: |
server:
  resources:
    requests:
      cpu: 50m
      memory: 96Mi
    limits:
      cpu: 100m
      memory: 96Mi
controller:
  resources:
    requests:
      cpu: 250m
      memory: 384Mi
    limits:
      cpu: 500m
      memory: 384Mi
applicationSet:
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 100m
      memory: 64Mi
notifications:
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 100m
      memory: 64Mi
repoServer:
  resources:
    requests:
      cpu: 10m
      memory: 128Mi
    limits:
      cpu: 50m
      memory: 128Mi
dex:
  resources:
    requests:
      cpu: 10m
      memory: 64Mi
    limits:
      cpu: 50m
      memory: 64Mi
redis:
  resources:
    requests:
      cpu: 100m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 64Mi